=pod

=head1 Nested Sections

Section 1

=head2 Section 1.1

Para 1.1

=head3 Section 1.1.1

Para 1.1.1

=head3 Section 1.1.2

Para 1.1.2

=head1 Section 2

Para 2

=head2 Section 2.1

Para 2.1

=head3 Section 2.1.1

Para 2.1.1

=head2 Section 2.2

Para 2.2

=head3 Section 2.2.1

Para 2.2.1

=head1 Section 3

Para 3

=cut